# Tekton PipelineRun for manual pipeline execution
# Use this file to manually trigger the CI/CD pipeline

apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: recommendations-manual-run-
  labels:
    app: recommendations
    tekton.dev/pipeline: recommendations-pipeline
spec:
  pipelineRef:
    name: recommendations-pipeline
  params:
    - name: repo-url
      value: https://github.com/CSCI-GA-2820-FA25-001/recommendations.git
    - name: branch
      value: master
    - name: image-name
      value: cluster-registry:5000/recommendations
    - name: image-tag
      value: "1.0"
    - name: database-uri
      value: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/postgres"
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
