apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cd-pipeline-vbe8sk
spec:
  params:
    - name: GIT_REPO
      value: 'https://github.com/CSCI-GA-2820-FA25-001/recommendations'
    - name: GIT_REF
      value: master
    - name: APP_NAME
      value: recommendations
    - name: IMAGE_NAME
      value: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest'
  pipelineRef:
    name: cd-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipeline-pvc
status:
  childReferences:
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: cd-pipeline-vbe8sk-git-clone
      pipelineTaskName: git-clone
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: cd-pipeline-vbe8sk-pylint
      pipelineTaskName: pylint
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: cd-pipeline-vbe8sk-pytest-env
      pipelineTaskName: pytest-env
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      name: cd-pipeline-vbe8sk-buildah
      pipelineTaskName: buildah
  completionTime: '2025-12-09T05:13:37Z'
  conditions:
    - lastTransitionTime: '2025-12-09T05:13:37Z'
      message: 'Tasks Completed: 4 (Failed: 0, Cancelled 0), Skipped: 0'
      reason: Succeeded
      status: 'True'
      type: Succeeded
  pipelineSpec:
    params:
      - description: The URL to the git repo
        name: GIT_REPO
        type: string
      - default: master
        description: The reference (branch or ref)
        name: GIT_REF
        type: string
      - default: recommendations
        description: Name of the application
        name: APP_NAME
        type: string
      - default: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest'
        description: The name of the image to build
        name: IMAGE_NAME
        type: string
    tasks:
      - name: git-clone
        params:
          - name: CRT_FILENAME
            value: ca-bundle.crt
          - name: HTTP_PROXY
            value: ''
          - name: HTTPS_PROXY
            value: ''
          - name: NO_PROXY
            value: ''
          - name: SUBDIRECTORY
            value: ''
          - name: USER_HOME
            value: /home/git
          - name: DELETE_EXISTING
            value: 'true'
          - name: VERBOSE
            value: 'false'
          - name: SSL_VERIFY
            value: 'true'
          - name: URL
            value: 'https://github.com/CSCI-GA-2820-FA25-001/recommendations'
          - name: REVISION
            value: master
          - name: REFSPEC
            value: ''
          - name: SUBMODULES
            value: 'true'
          - name: DEPTH
            value: '1'
          - name: SPARSE_CHECKOUT_DIRECTORIES
            value: ''
        taskRef:
          params:
            - name: kind
              value: task
            - name: name
              value: git-clone
            - name: namespace
              value: openshift-pipelines
          resolver: cluster
        workspaces:
          - name: output
            workspace: pipeline-workspace
      - name: pylint
        params:
          - name: image
            value: 'quay.io/rofrano/python:3.11-slim'
          - name: path
            value: service
          - name: args
            value: []
          - name: requirements-file
            value: requirements.txt
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: pylint
        workspaces:
          - name: source
            workspace: pipeline-workspace
      - name: pytest-env
        params:
          - name: pytest-args
            value: []
          - name: secret-name
            value: postgres-creds
          - name: secret-key
            value: database_uri
        runAfter:
          - git-clone
        taskRef:
          kind: Task
          name: pytest-env
        workspaces:
          - name: source
            workspace: pipeline-workspace
      - name: buildah
        params:
          - name: IMAGE
            value: 'image-registry.openshift-image-registry.svc:5000/zl3152-dev/recommendations:latest'
          - name: DOCKERFILE
            value: ./Dockerfile
          - name: BUILD_ARGS
            value:
              - ''
          - name: CONTEXT
            value: .
          - name: STORAGE_DRIVER
            value: vfs
          - name: FORMAT
            value: oci
          - name: BUILD_EXTRA_ARGS
            value: ''
          - name: PUSH_EXTRA_ARGS
            value: ''
          - name: SKIP_PUSH
            value: 'false'
          - name: TLS_VERIFY
            value: 'true'
          - name: VERBOSE
            value: 'false'
        runAfter:
          - pylint
          - pytest-env
        taskRef:
          params:
            - name: kind
              value: task
            - name: name
              value: buildah
            - name: namespace
              value: openshift-pipelines
          resolver: cluster
        workspaces:
          - name: source
            workspace: pipeline-workspace
    workspaces:
      - name: pipeline-workspace
  provenance:
    featureFlags:
      maxResultSize: 4096
      awaitSidecarReadiness: true
      coschedule: workspaces
      resultExtractionMethod: termination-message
      enforceNonfalsifiability: none
      enableAPIFields: beta
      runningInEnvWithInjectedSidecars: true
      verificationNoMatchPolicy: ignore
      enableProvenanceInStatus: true
  startTime: '2025-12-09T05:11:53Z'