# Tekton Tasks for Recommendations Service CI/CD Pipeline
# These tasks define the individual steps in the pipeline

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone
  labels:
    app: recommendations
spec:
  description: Clone the repository to workspace
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
    - name: branch
      type: string
      description: The git branch to clone
      default: master
  workspaces:
    - name: output
      description: The workspace to clone the repo into
  steps:
    - name: clone
      image: bitnami/git:latest
      script: |
        #!/bin/bash
        set -e
        echo "Cloning $(params.repo-url) branch $(params.branch)"
        git clone --depth 1 --branch $(params.branch) $(params.repo-url) $(workspaces.output.path)/source
        echo "Clone completed successfully"
        ls -la $(workspaces.output.path)/source

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint
  labels:
    app: recommendations
spec:
  description: Run linting checks with flake8 and pylint
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: flake8
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/bash
        set -e
        echo "Installing dependencies..."
        pip install --quiet flake8 pylint
        echo "Running flake8 syntax check..."
        flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "Running flake8 style check..."
        flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
        echo "Lint check passed!"

    - name: pylint
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/bash
        set -e
        pip install --quiet pylint pipenv
        pipenv install --system --dev --quiet
        echo "Running pylint..."
        pylint service tests --max-line-length=127 || true
        echo "Pylint check completed!"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tests
  labels:
    app: recommendations
spec:
  description: Run unit tests with pytest
  params:
    - name: database-uri
      type: string
      description: PostgreSQL connection string
      default: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/postgres"
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: pytest
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)/source
      env:
        - name: DATABASE_URI
          value: $(params.database-uri)
        - name: RETRY_COUNT
          value: "1"
      script: |
        #!/bin/bash
        set -e
        echo "Installing dependencies..."
        pip install --quiet pipenv
        pipenv install --system --dev --quiet
        echo "Running pytest..."
        pytest --pspec --cov=service --cov-report=term --cov-fail-under=95 --disable-warnings
        echo "Tests passed!"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
  labels:
    app: recommendations
spec:
  description: Build and push Docker image using Kaniko
  params:
    - name: image-name
      type: string
      description: The name of the image to build
      default: cluster-registry:5000/recommendations
    - name: image-tag
      type: string
      description: The tag for the image
      default: "1.0"
  workspaces:
    - name: source
      description: The workspace containing the source code
  results:
    - name: image-url
      description: The full URL of the built image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(workspaces.source.path)/source/Dockerfile
        - --context=$(workspaces.source.path)/source
        - --destination=$(params.image-name):$(params.image-tag)
        - --insecure
        - --skip-tls-verify
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
    - name: output-image-url
      image: busybox
      script: |
        #!/bin/sh
        echo -n "$(params.image-name):$(params.image-tag)" | tee $(results.image-url.path)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy
  labels:
    app: recommendations
spec:
  description: Deploy application to Kubernetes
  params:
    - name: manifest-dir
      type: string
      description: Directory containing Kubernetes manifests
      default: k8s
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/bin/bash
        set -e
        echo "Applying Kubernetes manifests from $(params.manifest-dir)/"
        kubectl apply -f $(params.manifest-dir)/
        echo "Waiting for deployment to be ready..."
        kubectl wait --for=condition=Available deployment/recommendations --timeout=120s || true
        echo "Deployment completed!"
        kubectl get pods -l app=recommendations
